name: 'Store Git credentials'
description: 'This action stores the Git credentials in the specified keychain.'
inputs:
  github-username:
    description: 'GitHub username'
    required: true
  github-password:
    description: >
      A personal access token with access to the GitHub repository.
    required: true
  keychain:
    description: >
      Path of the keychain to use. If omitted, the default login keychain is used.
    required: false
    default: ''
  keychain-password:
    description: >
      Password for the keychain if specified in the keychain parameter;
      default login keychain password if the kerchain parameter is omitted.
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "download"
  color: "orange"